sudo: required

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

before_script:
  - docker build -t javacard-gradle-template .

script:
  - docker run --user 0 javacard-gradle-template gradle check --info
  - docker run --user 0 javacard-gradle-template gradle buildJavaCard --info

notifications:
  email: false
